/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package co.cp.orderly.kafka.model.avro;
@org.apache.avro.specific.AvroGenerated
public enum ShopOrderStatus implements org.apache.avro.generic.GenericEnumSymbol<ShopOrderStatus> {
  PAID  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ShopOrderStatus\",\"namespace\":\"co.cp.orderly.kafka.model.avro\",\"symbols\":[\"PAID\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
