---
version: '3.8'
services:
  kafka-topics:
    image: ghcr.io/arm64-compat/confluentinc/cp-kafka:${KAFKA_VERSION}
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # block until kafka is reachable
      kafka-topics --bootstrap-server first-broker:9092 --list

      echo -e 'Deleting kafka topics'
      kafka-topics --bootstrap-server first-broker:9092 --topic payment-request --delete --if-exists
      kafka-topics --bootstrap-server first-broker:9092 --topic payment-response --delete --if-exists
      kafka-topics --bootstrap-server first-broker:9092 --topic shop-approval-request --delete --if-exists
      kafka-topics --bootstrap-server first-broker:9092 --topic shop-approval-response --delete --if-exists
      kafka-topics --bootstrap-server first-broker:9092 --topic customer --delete --if-exists

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server first-broker:9092 --create --if-not-exists --topic payment-request --replication-factor 3 --partitions 3
      kafka-topics --bootstrap-server first-broker:9092 --create --if-not-exists --topic payment-response --replication-factor 3 --partitions 3
      kafka-topics --bootstrap-server first-broker:9092 --create --if-not-exists --topic shop-approval-request --replication-factor 3 --partitions 3
      kafka-topics --bootstrap-server first-broker:9092 --create --if-not-exists --topic shop-approval-response --replication-factor 3 --partitions 3
      kafka-topics --bootstrap-server first-broker:9092 --create --if-not-exists --topic customer --replication-factor 3 --partitions 3


      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server first-broker:9092 --list
      "
    networks:
      - ${GLOBAL_NETWORK:-kafka}
